language: python
dist: focal

# Only build master, the version branches (e.g. 1.7.x), and
# version tags (which are apparently considered branches by travis)
branches:
    only:
        - master
        - /\d+\.\d+\.x/
        - /\d+\.\d+(\.\d+)?/


matrix:
    include:
        - python: 2.7
          env: TOXENV=py27 SODIUM_INSTALL=bundled
        - python: 3.5
          env: TOXENV=py35 SODIUM_INSTALL=bundled
        - python: 3.6
          env: TOXENV=py36 SODIUM_INSTALL=bundled
        - python: 3.7
          env: TOXENV=py37 SODIUM_INSTALL=bundled
        - python: 3.8
          env: TOXENV=py38 SODIUM_INSTALL=bundled
        - python: pypy2.7-7.3.1
          env: TOXENV=pypy SODIUM_INSTALL=bundled
        - python: 3.8
          env: TOXENV=py38 SODIUM_INSTALL=system
        - python: 3.8
          env: TOXENV=py38 SODIUM_INSTALL=bundled SODIUM_INSTALL_MINIMAL=1
        - python: 3.8
          env: TOXENV=docs
        - python: 3.8
          env: TOXENV=meta
        - python: 3.8
          env: 
          - TOXENV=py38 
          - SODIUM_INSTALL=bundled
          - BUILD_SDIST=true
          - BUILD_WHEEL=true
          dist: focal
          arch: arm64-graviton2
          virt: lxd
          group: edge
        - python: 3.8
          env: TOXENV=py38 SODIUM_INSTALL=system
          dist: focal
          arch: arm64-graviton2
          virt: lxd
          group: edge
        - python: 3.8
          env: TOXENV=py38 SODIUM_INSTALL=bundled SODIUM_INSTALL_MINIMAL=1
          dist: focal
          arch: arm64-graviton2
          virt: lxd
          group: edge

install: .travis/install.sh

script: 
  - LIBSODIUM_MAKE_ARGS="-j$(nproc)" tox
  - if [ "$BUILD_WHEEL" == "true" ]; then 
      cibuildwheel --output-dir dist ;
      python setup.py sdist;
    fi
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
deploy:
  provider: releases
  file:
  - dist/*.whl
  - dist/*.tar.gz
  file_glob: true
  on:
    repo: ssps12/pynacl
    tags: true
  skip_cleanup: true  

notifications:
  irc:
    channels:
      # This is set to a secure variable to prevent forks from notifying the
      # IRC channel whenever they fail a build. This can be removed when travis
      # implements https://github.com/travis-ci/travis-ci/issues/1094.
      # The value encrypted here was created via
      # travis encrypt "irc.freenode.org#cryptography-dev"
      - secure: "DjoeF3KknBb3hZjNhFdthtXM1rYscZ5hd9hzYyN006rOY4CxnshJVYFoRIAEfZ58H2kAB6ZBntLmmXpARYQD636YQY9RLN4GytFYjJF0lpD2OoS9XrOJNUl1LivR7yFarPucDFnzZKo20myelUDA/X7eh21c9G+JM3Vukq2jNog="
    use_notice: true
    skip_join: true
deploy:
  provider: pypi
  user: sakshi87
  password:
    secure: vV/Mi3XpNc+PwVVRQeLA3VCnPan+Y07GLSyVwb+BPe9iA3O2rruBYP8HQ6IqUfbWJ+pqBD6R9/Qwpcr7zcpFn/7SXQpEuAeW2mBV/w9xSAzSwRCt2SBhtnKnTfWva6rpdYlIm01K3yuV/s1cERmwXJg0Teq7gIw0ioSG2FQcULLABgYrpPuOd0DfcFy5/Yk2Q14BJqRETfWjEAfGWsuWiN2cEmy5M9Z2gCiiXyWNN/vCB4GDRP2giSTNv+xnIU94EjGAhkFzsg3pbQXyXGqdMFvOFIeNNAE0dd90GgnsHtt/tgy+9FU75E6oQh0tJ47HbnQLYSDDNHhd4Hb5ZemdF1UTy260q8mOSIaI2KAYEXY/323cLnlh6ZHuV6SpKqK5gy5VgoeobltgT/iLxl53fmf9OLmvdaG+g01KW9DRIfPUoervMdu+FIT3/Xb4hCFlw37lpAxaRT4NzCo/Ogh5n9ULMP3IewuXt3w438zo75tFG93xt8gt4ob8wC5D2h4dLe5uW3rcnlg5jKAYTQkzTeeJe+7zh7YvSOsjAPeLBEVSpYdTkWnmaz0m0sWVkmXMDOR4hSrL/wQBjeRNy86IYnXtAmjSqzdbx8ZBPB3iSu5Rjeug4C/OQADs6qgy5cDZpdbBDO7xe8lc86IcjWYUqVnodEdKVVdousyq+fAN4Fg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ssps12/pynacl
  skip_cleanup: 'true'    
